# Generated by Django 3.0.7 on 2020-07-14 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=4)),
                ('tot_players', models.IntegerField()),
                ('players_in_lobby', models.IntegerField(null=True)),
                ('game_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=15)),
                ('text_clues', models.CharField(max_length=3000)),
                ('submit_state', models.IntegerField()),
                ('game_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptionary.Game')),
            ],
        ),
    ]
